# Generated by Django 2.1.3 on 2018-12-11 21:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AppearanceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(blank=True)),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrgType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Superfrog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SuperfrogAppearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateTimeField(default=datetime.datetime(2018, 12, 11, 15, 57, 9, 190707))),
                ('superfrog', models.ForeignKey(on_delete='NULL', to='api.Superfrog')),
            ],
        ),
        migrations.CreateModel(
            name='TeamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Event')),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('parking_info', models.CharField(blank=True, max_length=255)),
                ('performance_required', models.BooleanField(default=False)),
                ('location_for_belongings', models.CharField(blank=True, max_length=255)),
                ('expenses_and_benefits', models.CharField(blank=True, max_length=255)),
                ('outside_orgs', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('org_type', models.ForeignKey(blank=True, on_delete='NULL', to='api.OrgType')),
                ('status', models.ForeignKey(default=1, on_delete='NULL', to='api.AppearanceStatus')),
                ('team_type', models.ForeignKey(blank=True, on_delete='NULL', to='api.TeamType')),
            ],
            bases=('api.event',),
        ),
        migrations.AddField(
            model_name='superfrogappearance',
            name='appearance',
            field=models.ForeignKey(on_delete='CASCADE', to='api.Appearance'),
        ),
        migrations.AddField(
            model_name='superfrog',
            name='appearances',
            field=models.ManyToManyField(through='api.SuperfrogAppearance', to='api.Appearance'),
        ),
    ]
