# Generated by Django 2.1.5 on 2019-02-25 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appearance',
            old_name='customers',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='superfrogappearance',
            name='date_assigned',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 17, 54, 35, 664880)),
        ),
    ]
