# Generated by Django 2.1.3 on 2019-01-24 21:45

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='customers',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete='NULL', to='api.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='superfrogappearance',
            name='date_assigned',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 24, 21, 44, 47, 931665)),
        ),
    ]
