# Generated by Django 2.1.3 on 2019-01-18 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190102_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='customers',
            field=models.ForeignKey(default=0, on_delete='CASCADE', to='api.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='superfrogappearance',
            name='date_assigned',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 19, 49, 17, 720878)),
        ),
    ]
