# Generated by Django 2.1.3 on 2018-11-28 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181128_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appearance',
            old_name='event_id',
            new_name='event',
        ),
        migrations.AlterField(
            model_name='superfrogappearance',
            name='date_assigned',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 28, 14, 34, 17, 824971)),
        ),
    ]
