# Generated by Django 2.1.3 on 2019-01-18 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190117_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='customers',
            field=models.ForeignKey(on_delete='NULL', to='api.Customer'),
        ),
        migrations.AlterField(
            model_name='superfrogappearance',
            name='date_assigned',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 19, 53, 28, 692827)),
        ),
    ]
