# Generated by Django 2.1.3 on 2018-11-29 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181128_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppearanceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='superfrogappearance',
            name='date_assigned',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 29, 13, 59, 35, 325888)),
        ),
        migrations.AddField(
            model_name='appearance',
            name='status',
            field=models.ForeignKey(default=0, on_delete='NULL', to='api.AppearanceStatus'),
            preserve_default=False,
        ),
    ]
