# Generated by Django 2.1.3 on 2019-01-24 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190124_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superfrogappearance',
            name='date_assigned',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 24, 21, 49, 49, 590898)),
        ),
    ]
