# Generated by Django 2.1.5 on 2019-02-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190225_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete='NULL', to='api.Customer'),
        ),
    ]
