# Generated by Django 2.1.3 on 2019-01-27 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190121_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superfrogappearance',
            name='date_assigned',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 27, 15, 43, 21, 780465)),
        ),
    ]
