# Generated by Django 2.1.5 on 2019-03-07 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190226_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appearance',
            old_name='location_for_belongings',
            new_name='special_instructions',
        ),
        migrations.AlterField(
            model_name='appearance',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Customer'),
        ),
        migrations.AlterField(
            model_name='superfrogappearance',
            name='appearance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Appearance'),
        ),
        migrations.AlterField(
            model_name='superfrogappearance',
            name='superfrog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Superfrog'),
        ),
    ]
