# Generated by Django 2.1.3 on 2019-01-29 22:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190124_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='event_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='event_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.Event'),
        ),
    ]
