# Generated by Django 2.1.7 on 2019-03-15 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190306_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superfrog',
            name='email',
        ),
        migrations.RemoveField(
            model_name='superfrog',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='superfrog',
            name='id',
        ),
        migrations.RemoveField(
            model_name='superfrog',
            name='last_name',
        ),
        migrations.AddField(
            model_name='superfrog',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
