# Generated by Django 2.1.3 on 2019-01-29 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190129_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superfrogappearance',
            name='date_assigned',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
