# Generated by Django 2.1.5 on 2019-03-11 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190306_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superfrogappearance',
            name='date_assigned',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
