# Generated by Django 2.1.7 on 2019-03-17 20:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190315_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superfrog',
            name='appearances',
        ),
        migrations.RemoveField(
            model_name='superfrog',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='superfrog',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='superfrogappearance',
            name='date_assigned',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
