# Generated by Django 2.1.7 on 2019-03-17 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190317_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='id',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='phone',
        ),
        migrations.AddField(
            model_name='admin',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
