# Generated by Django 2.1.7 on 2019-03-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190317_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
