# Generated by Django 2.1.5 on 2019-02-01 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190131_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superfrogappearance',
            name='appearance',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='api.Appearance'),
        ),
        migrations.AlterField(
            model_name='superfrogappearance',
            name='date_assigned',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 31, 20, 2, 47, 847948)),
        ),
        migrations.AlterField(
            model_name='superfrogappearance',
            name='superfrog',
            field=models.ForeignKey(null=True, on_delete='NULL', to='api.Superfrog'),
        ),
    ]
