# Generated by Django 2.1.7 on 2019-03-17 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_admin_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superfrog',
            name='appearances',
            field=models.ManyToManyField(through='api.SuperfrogAppearance', to='api.Appearance'),
        ),
    ]
