# Generated by Django 2.1.5 on 2019-03-21 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190317_2210'),
        ('api', '0010_auto_20190311_1858'),
    ]

    operations = [
    ]
