# Generated by Django 2.1.5 on 2019-03-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20190321_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='superfrog',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='superfrog',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='superfrog',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='superfrog',
            name='zipCode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
