# Generated by Django 2.1.7 on 2019-04-03 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190331_0510'),
        ('api', '0017_auto_20190325_1957'),
    ]

    operations = [
    ]
