# Generated by Django 2.1.3 on 2019-04-03 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_superfrogclass'),
        ('api', '0017_auto_20190325_1957'),
    ]

    operations = [
    ]
