# Generated by Django 2.1.5 on 2019-04-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_merge_20190403_1921'),
        ('api', '0018_merge_20190403_1735'),
    ]

    operations = [
    ]
