# Generated by Django 2.1.5 on 2019-04-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_merge_20190404_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showgirl_captain_email', models.EmailField(max_length=255, verbose_name='Showgirl Captain Email')),
                ('cheerleader_captain_email', models.EmailField(max_length=255, verbose_name='Showgirl Captain Email')),
                ('fall_semester_start', models.DateTimeField()),
                ('fall_semester_end', models.DateTimeField()),
                ('spring_semester_start', models.DateTimeField()),
                ('spring_semester_end', models.DateTimeField()),
            ],
        ),
    ]
