# Generated by Django 2.1.5 on 2019-04-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_constants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='mileage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
