# Generated by Django 2.1.7 on 2019-04-23 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190411_0350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Constants',
            new_name='Constant',
        ),
    ]
