# Generated by Django 2.1.5 on 2019-04-23 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20190422_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superfrog',
            name='street',
        ),
    ]
