# Generated by Django 2.1.5 on 2019-04-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_superfrog_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='superfrog',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
