# Generated by Django 2.1.5 on 2019-04-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_superfrog_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='eligable_for_pay',
            field=models.BooleanField(default=True),
        ),
    ]
