# Generated by Django 2.1.5 on 2019-04-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_superfrog_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='cost',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='mileage',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
