# Generated by Django 2.1.5 on 2019-04-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20190424_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
