# Generated by Django 2.1.5 on 2019-04-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20190424_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='constant',
            name='spirit_private_lg_rate',
            field=models.DecimalField(decimal_places=2, default=225.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constant',
            name='spirit_private_sm_rate',
            field=models.DecimalField(decimal_places=2, default=175.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constant',
            name='spirit_public_lg_rate',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constant',
            name='spirit_public_sm_rate',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
            preserve_default=False,
        ),
    ]
