# Generated by Django 2.1.5 on 2019-04-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20190424_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constant',
            name='fall_semester_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='constant',
            name='fall_semester_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='constant',
            name='spring_semester_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='constant',
            name='spring_semester_start',
            field=models.DateField(),
        ),
    ]
