# Generated by Django 2.1.5 on 2019-05-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_appearance_eligable_for_pay'),
        ('api', '0032_constant_appearance_max_len'),
    ]

    operations = [
    ]
